### ISSUE TITLE
Issues with the NavBar

### ISSUE THREAD

**Issue by Steve-Leke** [mellychat/webapp#30]
Somehow during the refactoring of patientSignUp.html, the navbar fails to show. 

You can't see the text nor the logo, and when you click where the text should be, it directs you to a missing page

Potential Solutions:
- Add "/" in front of the hrefs for the navbar.
- Double-check that the bootstrap code is loading in corrctly.

@Mannendri this was your pull request, so could you look into it? Let me know if you need some help!

**Comment by Mannendri** [comment]
I will look into this as soon as possible.

**Comment by j0n3lson** [comment]
I think Steve already sent a PR for this.

**Comment by j0n3lson** [comment]
Ping @Steve-Leke you want to take another shot at this. Can you confirm your two open PRs are related to this?

**Comment by Mannendri** [comment]
Okay, so I know that Lilly mentioned background colors: https://github.com/mellychat/webapp/pull/47#discussion_r549050419

But I'm not sure that that is the issue because in prSignUp.html, the background color of the page is white (and so is the background color of the navbar). In prSignUp.html, the nav links are black and then blue when you hover over them.

That being said, I still haven't figured out the problem, but I will keep trying.

**Comment by Steve-Leke** [comment]
> Okay, so I know that Lilly mentioned background colors: [#47 (comment)](https://github.com/mellychat/webapp/pull/47#discussion_r549050419)
> 
> But I'm not sure that that is the issue because in prSignUp.html, the background color of the page is white (and so is the background color of the navbar). In prSignUp.html, the nav links are black and then blue when you hover over them.
> 
> That being said, I still haven't figured out the problem, but I will keep trying.

I've come close to figuring out the problem. I strongly believe it relates to the way things are being rendered on to page. I will try again to fix it.
